version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pulse_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pulse_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pulse_password}
      POSTGRES_DB: ${POSTGRES_DB:-pulse_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pulse_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulse_network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: pulse_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulse_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  pulse_network:
    driver: bridge