apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pulse/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://pulse_user:$(POSTGRES_PASSWORD)@postgres:5432/pulse_db"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: REDIS_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: CELERY_RESULT_BACKEND
        - name: NEWSAPI_KEY
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: NEWSAPI_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: OPENAI_API_KEY
        - name: HF_API_KEY
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: HF_API_KEY
        - name: X_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: X_BEARER_TOKEN
        - name: X_API_KEY
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: X_API_KEY
        - name: X_API_SECRET
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: X_API_SECRET
        - name: X_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: X_ACCESS_TOKEN
        - name: X_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: X_ACCESS_TOKEN_SECRET
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pulse-secrets
              key: JWT_SECRET_KEY
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: LOG_LEVEL
        - name: MOCK_MODE
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: MOCK_MODE
        - name: ENABLE_METRICS
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: ENABLE_METRICS
        - name: METRICS_PORT
          valueFrom:
            configMapKeyRef:
              name: pulse-config
              key: METRICS_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pulse
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: pulse
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80